// create user
const WEAK_PASSWORD_ERROR = 'WEAK_PASSWORD_ERROR';
const EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE';
// log in
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const WRONG_PASSWORD = 'WRONG_PASSWORD';
// Google sign and Sign out in error
const TRY_AGAIN = "TRY_AGAIN";
// Authentication message
const CAN_NOT_SEND_CONFIRMATION = "CAN_NOT_SEND_CONFIRMATION";
// getting users
const CAN_NOT_LOAD_USERS = 'CAN_NOT_LOAD_USERS';
const CAN_NOT_LOAD_USER = 'CAN_NOT_LOAD_USER';
// uploading photo
const PHOTO_WAS_NOT_UPLOADED = 'PHOTO_WAS_NOT_UPLOADED';
const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';
// Room
const CAN_NOT_LOAD_ROOMS = 'CAN_NOT_GET_ROOMS';
const ROOM_WAS_NOT_CREATED = 'ROOM_WAS_NOT_CREATED';
const YOU_HAVE_TO_VERIFY_YOUR_ACCOUNT_FIRST = 'YOU_HAVE_TO_VERIFY_YOUR_ACCOUNT_FIRST';
// Topic
const CAN_NOT_LOAD_TOPICS = 'CAN_NOT_GET_TOPICS';
const TOPIC_WAS_NOT_CREATED = 'TOPIC_WAS_NOT_CREATED';
// Chat
const CAN_NOT_SEND_MESSAGE = 'CAN_NOT_SEND_MESSAGE';
const ROOM_NOT_FOUND = 'ROOM_NOT_FOUND';
const ROOM_UPDATE_FAILED = 'ROOM_UPDATE_FAILED';
const ROOM_DELETE_FAILED = 'ROOM_DELETE_FAILED';
// Verification
const CAN_NOT_SEND_VERIFICATION = 'CAN_NOT_SEND_VERIFICATION';
// Profile
const PROFILE_ERROR = 'PROFILE_ERROR';

// Successful operations
